name: wakDak
description: A new Flutter project.

publish_to: "none"

version: 1.0.6+7

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cached_network_image: ^3.1.0+1
  http: ^0.13.3
  flutter_svg: ^2.0.2
  shared_preferences: ^2.0.9
  google_maps_flutter: ^2.1.1
  url_launcher: ^6.0.16
  image: ^4.0.15
  firebase_auth: ^4.1.3
  firebase_core: ^2.3.0
  firebase_messaging: ^14.1.1
  google_sign_in: ^6.0.2
  apple_sign_in_safety: ^0.0.6
  sign_in_with_apple: ^5.0.0
  flutter_html: ^3.0.0-beta.2
  flutter_local_notifications: ^16.2.0

  #google places
  rxdart: ^0.27.4
  google_maps_webservice: ^0.0.20-nullsafety.0
  google_api_headers: ^3.1.0

  #current location
  geolocator: ^10.1.0
  geocoding: ^2.0.1
  location:
  location_geocoder: ^1.0.5
  flutter_bloc: ^8.0.1
  hive_flutter: ^1.0.0
  hive: ^2.0.4
  image_picker: ^1.0.4
  internet_connection_checker: ^1.0.0+1
  intl_phone_field: ^3.1.0
  launch_review: ^3.0.1
  otp_autofill: ^3.0.0
  sms_autofill: ^2.2.0
  path_provider: ^2.0.2
  pin_code_fields: ^8.0.1
  webview_flutter: ^4.0.6
  connectivity_plus: ^5.0.2
  google_fonts: ^4.0.3
  pin_input_text_field: ^4.1.1
  permission_handler: ^11.0.0
  provider: ^6.0.2
  carousel_slider: ^4.0.0
  share_plus: ^7.0.0
  flutter_exif_rotation: ^0.5.1
  mime_type: ^1.0.0
  shimmer: ^3.0.0
  flutter_rating_bar: ^4.0.0
  flutter_stripe: ^9.0.0+1
  paytm: ^3.0.1
  razorpay_flutter: ^1.2.7
  flutter_paystack: ^1.0.7
  flutter_html_to_pdf: ^0.7.0
  open_filex: ^4.3.1
  flutter_downloader: ^1.7.1
  file_picker: ^6.1.1
  google_places_flutter: ^2.0.5
  package_info_plus: ^4.0.0
  speech_to_text: ^6.1.1

  #google_maps_place_picker_mb:
  path_drawing: ^1.0.1
  webview_flutter_android: ^3.3.1
  webview_flutter_wkwebview: ^3.2.0
  image_pixels: ^3.0.0
  lottie: ^2.3.2
  google_maps_widget: ^1.0.5+1

  #flutter_polyline_points: ^1.0.0
  easy_stepper: ^0.8.2
  image_cropper: ^4.0.1
  external_path: ^1.0.3
  flutter_widget_from_html: ^0.14.11

dependency_overrides:
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/WakDak.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logos/WakDak.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/logos/WakDak.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logos/WakDak.png"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/image/
    - assets/images/image/0.75x/
    - assets/images/image/1.0x/
    - assets/images/image/1.5x/
    - assets/images/image/2.0x/
    - assets/images/image/3.0x/
    - assets/images/image/4.0x/
    - assets/images/svg/
    - assets/eRestro.db
    - assets/images/json/
    - assets/languages/
    - assets/logos/

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/font/Quicksand-Regular.ttf
        - asset: assets/font/Quicksand-Bold.ttf
          weight: 700
        - asset: assets/font/Quicksand-SemiBold.ttf
          weight: 600
        - asset: assets/font/Quicksand-Light.ttf
          weight: 300
        - asset: assets/font/Quicksand-Medium.ttf
          weight: 500
