// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUVgXF7a0pONOqLJ_kJ-zu-c2Ey5hUI-Y',
    appId: '1:952751070155:web:604894c3b59c25f1ba344e',
    messagingSenderId: '952751070155',
    projectId: 'all-your-look',
    authDomain: 'all-your-look.firebaseapp.com',
    storageBucket: 'all-your-look.appspot.com',
    measurementId: 'G-GV853GKML3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKXbM0YUOrbnwAQEBUgojAHUM9trEHRoQ',
    appId: '1:952751070155:android:a33dd607d23b3b58ba344e',
    messagingSenderId: '952751070155',
    projectId: 'all-your-look',
    storageBucket: 'all-your-look.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnHSLck4ikoo8K56PLJvWfkggyIXduACU',
    appId: '1:952751070155:ios:73a959f90115fcd3ba344e',
    messagingSenderId: '952751070155',
    projectId: 'all-your-look',
    storageBucket: 'all-your-look.appspot.com',
    androidClientId: '952751070155-4dsk2ft1k53a5q0chrk5e07ak0mc5hd7.apps.googleusercontent.com',
    iosClientId: '952751070155-p93mdrsbmsr5niok99oqmiqvcohmb38g.apps.googleusercontent.com',
    iosBundleId: 'com.wakdak.wakdakCustomer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnHSLck4ikoo8K56PLJvWfkggyIXduACU',
    appId: '1:952751070155:ios:73a959f90115fcd3ba344e',
    messagingSenderId: '952751070155',
    projectId: 'all-your-look',
    storageBucket: 'all-your-look.appspot.com',
    androidClientId: '952751070155-4dsk2ft1k53a5q0chrk5e07ak0mc5hd7.apps.googleusercontent.com',
    iosClientId: '952751070155-p93mdrsbmsr5niok99oqmiqvcohmb38g.apps.googleusercontent.com',
    iosBundleId: 'com.wakdak.wakdakCustomer',
  );
}
